---@class diagnostic nvim diagnostic https://neovim.io/doc/user/diagnostic.html#diagnostic-structure
---@field message string
---@field source? number -- linter of LSP name
---@field code? string -- rule id
---@field bufnr number
